* Sparse machine matter

2-Codex is a directory for content that is primarily intended for consumption by computers, not humans. 

=2-Codex= is focused on the machine-readable aspect of a file, such as its metadata fields, version history and path.

Prose doesn't belong.  =2-Codex= isn't choked by large amounts of low-priority prose reading.  This keeps your important technical information sparse and accessible.

Code snippets belong here, before they migrate to their own repos.

Paths belong here.  Domain names don't, but IP addresses do.

Information about files stored outside Textmind belongs here.  The goal is to be a sparse index of files stored outside Textmind, for easy reference.  If you have copious prose notes about a file, link to the file's =2-Codex= entry (or merely allude to it) but store the prose in e.g.  =9-Background=.  

For example, say you took notes on the movie Titanic.  Your notes about the movie would belong under =7-Names=.  The path of the video file, and notes about torrenting it, go under =2-Codex=.  
