* Your personal VIP workspace

Think of Persinter as your personal workspace, free of the restrictions that bind the rest of 10 Bins.  Here you may break the rules to get stuff done.

"Persinter" is a portmanteau of "personal" and "interstitial".

"Personal" means info that is highly specific or important to you.  For example, the eruption of a volcano next door is not specific to you, but it is very important to you.  Your current plans and problems are both specific and important to you, such as escaping said volcano.

"Interstitial" means info that overlaps multiple 10 Bins.  If an unimportant object is difficult to categorize, just throw it anywhere that's a passable fit.  Persinter is for objects that are at least moderately important.

Objects in Persinter either remain there, or are decomposed for refiling elsewhere.

In the aforementioned Vesuvian emergency, you are advised to create the directory =3-Persinter/Volcano= and throw your critical escape info there.  Then focus on that directory and ignore the rest of 10 Bins.

Once you are safely beyond the disaster zone, you may refile the contents of =3-Persinter/Volcano= at your leisure.  

As you can see from the example, Persinter evolves more rapidly than the rest of 10 Bins, to sync with what's at the top of your mind.  It is a key synthetic overview of your Textmind.

Persinter is also a good place to put permanent files that you frequently access, for easy retrieval.
